# Github Actions

name: ARGOCD GITOPS

on: [create, delete] # runs your workflow when someone creates/deletes a Git reference (Git branch or tag) in the workflow's repository.

jobs:
  gitops: 
    name: ArgoCD GitOps
    if: github.event.ref_type == 'branch' # checking that action was not triggered by tag
    runs-on: 'ubuntu-latest'
    steps:
    
      - name: Checkout ArgoCD GitOps repo
        uses: actions/checkout@master
        with:
          repository: devops-systems/argocd-gitops
          ref: 'main'
          token:  ${{ secrets.GITOPS_TOKEN }}
          path: 'gitops'
          
      - name: Generate variables                 
        run: |
          if [ ${{ github.event.ref }} == 'main' ] 
          then
            echo "ARGOCD_APPLICATION_TEMP_FILE=configs/templates/argocd_gitops_prod.yaml" >> $GITHUB_ENV
            echo "ARGOCD_APPLICATION_FOLDER=apps/apps-prod" >> $GITHUB_ENV
            echo "CLEAN_BRANCH=${{ github.event.ref }}" >> $GITHUB_ENV # need for file name
          elif [ ${{ github.event.ref }} == 'dev' ]
          then
            echo "ARGOCD_APPLICATION_TEMP_FILE=configs/templates/argocd_gitops_dev.yaml" >> $GITHUB_ENV
            echo "ARGOCD_APPLICATION_FOLDER=apps/apps-dev" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV # need for envsubst templates
            echo "CLEAN_BRANCH=${{ github.event.ref }}" >> $GITHUB_ENV # need for file name
          else
            echo "ARGOCD_APPLICATION_TEMP_FILE=configs/templates/argocd_gitops_features.yaml" >> $GITHUB_ENV
            echo "ARGOCD_APPLICATION_FOLDER=apps/apps-features" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV # need for envsubst templates
            export CLEAN_BRANCH=${{ github.event.ref }} # need for envsubst templates and file name
            export CLEAN_BRANCH=${CLEAN_BRANCH//[^[:alnum:]]/} # remove special characters
            echo "CLEAN_BRANCH=${CLEAN_BRANCH,,}" >> $GITHUB_ENV # move in lowercase
          fi
          echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV # need for envsubst templates
          echo "BRANCH=${{ github.event.ref }}" >> $GITHUB_ENV # need for envsubst templates
          
      - name: Generate application file 
        if: github.event_name == 'create'
        working-directory: gitops
        run: |
          envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < $ARGOCD_APPLICATION_TEMP_FILE > $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml
          cat $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml
          
      - name: Delete application file 
        if: github.event_name == 'delete'
        working-directory: gitops
        run: |
          if [ -f "$ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml" ]
          then
              echo "The file $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml exists."
              cat $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml
              rm $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml
          else
            echo "The file $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml doesn't exists."
            exit 1 
          fi
          
      - name: Commit & Push changes to ArgoCD GitOps
        working-directory: gitops
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.GITOPS_EMAIL }}"
          git add $ARGOCD_APPLICATION_FOLDER/$REPO-$CLEAN_BRANCH.yaml
          git commit -m "GitHub Actions Bot - $(date)"
          git push