apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: example2
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - web/values.yaml
        - web/dev/values.yaml
