apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-prod
  namespace: argocd
spec:
  description: Project Prod
  sourceRepos:
  - '*'
  destinations:
  - namespace: prod
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
