apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $REPO-$BRANCH
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .infra/
    repoURL: https://github.com/devops-systems/$REPO.git
    targetRevision: $BRANCH
    helm:
      valueFiles:
        - values.yaml
      values: |
        container:
          tag: $IMAGE_TAG
  destination:
    namespace: $BRANCH
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
