---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: app2-DO-917
  namespace: argocd
spec:
  destination:
    namespace: DO-917
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      values: |
        container:
          tag: "latest"
    path: .infra/
    repoURL: https://github.com/devops-systems/app2.git
    targetRevision: DO-917
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
