apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-do917
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .infra/
    repoURL: https://github.com/devops-systems/app2.git
    targetRevision: do917
    helm:
      valueFiles:
        - values.yaml
      values: |
        container:
          tag: latest
  destination:
    namespace: do917
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
